---
apiVersion: v1
kind: flag-configuration

flag: ABC flag

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 52
    option: true
  - percentage: 48
    option: false

conditions: []
