---
apiVersion: v1
kind: flag-configuration

flag: ABC flag

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 58
    option: true
  - percentage: 42
    option: false

conditions: []
