---
apiVersion: v1
kind: flag-configuration

flag: flag111

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 50
    option: true
  - percentage: 50
    option: false

conditions: []
