---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: flag111

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: isLoggedIn
          operator: is-true
      - anyOf:
          - group:
              id: 83f5cc01-05cf-427d-561a-ed34f6655093
          - group:
              id: 3f140235-04c7-4593-78c5-4d0c61e337b3
          - group:
              id: d0e7ed70-0573-48ab-42b3-b36a59e825b2
          - group:
              id: 1a1e3611-cab0-4988-95a9-d220100e91ca
    flagValue: false
