---
apiVersion: v1
kind: flag-configuration

flag: numberSplit

enabled: true

defaultValue: 21

conditions:
  - allOf:
      - property:
          name: rox.app_release
          operator: regex
          operands:
              - "1231232222"
    flagValue:
      valueWrittenInCode: true
