---
apiVersion: v1
kind: flag-configuration

flag: numberSplit

enabled: false

defaultValue: 21

conditions:
  - allOf:
      - property:
          name: rox.app_release
          operator: regex
          operands:
              - 123123222w
    flagValue:
      valueWrittenInCode: true
