---
apiVersion: v1
kind: flag-configuration

flag: numberSplit

enabled: false

defaultValue: 21

conditions:
  - allOf:
      - anyOf:
          - group:
              name: test
      - property:
          name: rox.now2
          operator: after
          operands:
              - "2024-08-12T21:00:00.000Z"
    flagValue:
      valueWrittenInCode: true
  - allOf:
      - anyOf:
          - group:
              name: parent
    flagValue:
      valueWrittenInCode: true
